-- XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
-- > Les n° auto pour des attributs non clé primaire ont été transformés en INTEGER.
-- > Les tables générées sont de type InnoDb.
-- > Les clés étrangères ne sont gérées que si MySql gère les tables InnoDb.
-- XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
set names 'utf8';
insert into `FAMILLE`(`FAM_CODE`,`FAM_LIBELLE`) values('AA','Antalgiques en association');
insert into `FAMILLE`(`FAM_CODE`,`FAM_LIBELLE`) values('AAA','Antalgiques antipyrétiques en association');
insert into `FAMILLE`(`FAM_CODE`,`FAM_LIBELLE`) values('AAC','Antidépresseur d''action centrale');
insert into `FAMILLE`(`FAM_CODE`,`FAM_LIBELLE`) values('AAH','Antivertigineux antihistaminique H1');
insert into `FAMILLE`(`FAM_CODE`,`FAM_LIBELLE`) values('ABA','Antibiotique antituberculeux');
insert into `FAMILLE`(`FAM_CODE`,`FAM_LIBELLE`) values('ABC','Antibiotique antiacnéique local');
insert into `FAMILLE`(`FAM_CODE`,`FAM_LIBELLE`) values('ABP','Antibiotique de la famille des béta-lactamines (pénicilline A)');
insert into `FAMILLE`(`FAM_CODE`,`FAM_LIBELLE`) values('AFC','Antibiotique de la famille des cyclines');
insert into `FAMILLE`(`FAM_CODE`,`FAM_LIBELLE`) values('AFM','Antibiotique de la famille des macrolides');
insert into `FAMILLE`(`FAM_CODE`,`FAM_LIBELLE`) values('AH','Antihistaminique H1 local');
insert into `FAMILLE`(`FAM_CODE`,`FAM_LIBELLE`) values('AIM','Antidépresseur imipraminique (tricyclique)');
insert into `FAMILLE`(`FAM_CODE`,`FAM_LIBELLE`) values('AIN','Antidépresseur inhibiteur sélectif de la recapture de la sérotonine');
insert into `FAMILLE`(`FAM_CODE`,`FAM_LIBELLE`) values('ALO','Antibiotique local (ORL)');
insert into `FAMILLE`(`FAM_CODE`,`FAM_LIBELLE`) values('ANS','Antidépresseur IMAO non sélectif');
insert into `FAMILLE`(`FAM_CODE`,`FAM_LIBELLE`) values('AO','Antibiotique ophtalmique');
insert into `FAMILLE`(`FAM_CODE`,`FAM_LIBELLE`) values('AP','Antipsychotique normothymique');
insert into `FAMILLE`(`FAM_CODE`,`FAM_LIBELLE`) values('AUM','Antibiotique urinaire minute');
insert into `FAMILLE`(`FAM_CODE`,`FAM_LIBELLE`) values('CRT','Corticoïde, antibiotique et antifongique à  usage local');
insert into `FAMILLE`(`FAM_CODE`,`FAM_LIBELLE`) values('HYP','Hypnotique antihistaminique');
insert into `FAMILLE`(`FAM_CODE`,`FAM_LIBELLE`) values('PSA','Psychostimulant, antiasthénique');

insert into `MEDICAMENT`(`MED_DEPOTLEGAL`,`MED_NOMCOMMERCIAL`,`FAM_CODE`,`MED_COMPOSITION`,`MED_EFFETS`,`MED_CONTREINDIC`) values('3MYC7','TRIMYCINE','CRT','Triamcinolone (acétonide) + Néomycine + Nystatine','Ce médicament est un corticoïde à  activité forte ou très forte associé à  un antibiotique et un antifongique, utilisé en application locale dans certaines atteintes cutanées surinfectées.','Ce médicament est contre-indiqué en cas d''allergie à  l''un des constituants, d''infections de la peau ou de parasitisme non traités, d''acné. Ne pas appliquer sur une plaie, ni sous un pansement occlusif.');
insert into `MEDICAMENT`(`MED_DEPOTLEGAL`,`MED_NOMCOMMERCIAL`,`FAM_CODE`,`MED_COMPOSITION`,`MED_EFFETS`,`MED_CONTREINDIC`) values('ADIMOL9','ADIMOL','ABP','Amoxicilline + Acide clavulanique','Ce médicament, plus puissant que les pénicillines simples, est utilisé pour traiter des infections bactériennes spécifiques.','Ce médicament est contre-indiqué en cas d''allergie aux pénicillines ou aux céphalosporines.');
insert into `MEDICAMENT`(`MED_DEPOTLEGAL`,`MED_NOMCOMMERCIAL`,`FAM_CODE`,`MED_COMPOSITION`,`MED_EFFETS`,`MED_CONTREINDIC`) values('AMOPIL7','AMOPIL','ABP','Amoxicilline','Ce médicament, plus puissant que les pénicillines simples, est utilisé pour traiter des infections bactériennes spécifiques.','Ce médicament est contre-indiqué en cas d''allergie aux pénicillines. Il doit être administré avec prudence en cas d''allergie aux céphalosporines.');
insert into `MEDICAMENT`(`MED_DEPOTLEGAL`,`MED_NOMCOMMERCIAL`,`FAM_CODE`,`MED_COMPOSITION`,`MED_EFFETS`,`MED_CONTREINDIC`) values('AMOX45','AMOXAR','ABP','Amoxicilline','Ce médicament, plus puissant que les pénicillines simples, est utilisé pour traiter des infections bactériennes spécifiques.','La prise de ce médicament peut rendre positifs les tests de dépistage du dopage.');
insert into `MEDICAMENT`(`MED_DEPOTLEGAL`,`MED_NOMCOMMERCIAL`,`FAM_CODE`,`MED_COMPOSITION`,`MED_EFFETS`,`MED_CONTREINDIC`) values('AMOXIG12','AMOXI Gé','ABP','Amoxicilline','Ce médicament, plus puissant que les pénicillines simples, est utilisé pour traiter des infections bactériennes spécifiques.','Ce médicament est contre-indiqué en cas d''allergie aux pénicillines. Il doit être administré avec prudence en cas d''allergie aux céphalosporines.');
insert into `MEDICAMENT`(`MED_DEPOTLEGAL`,`MED_NOMCOMMERCIAL`,`FAM_CODE`,`MED_COMPOSITION`,`MED_EFFETS`,`MED_CONTREINDIC`) values('APATOUX22','APATOUX Vitamine C','ALO','Tyrothricine + Tétracaïne + Acide ascorbique (Vitamine C)','Ce médicament est utilisé pour traiter les affections de la bouche et de la gorge.','Ce médicament est contre-indiqué en cas d''allergie à  l''un des constituants, en cas de phénylcétonurie et chez l''enfant de moins de 6 ans.');
insert into `MEDICAMENT`(`MED_DEPOTLEGAL`,`MED_NOMCOMMERCIAL`,`FAM_CODE`,`MED_COMPOSITION`,`MED_EFFETS`,`MED_CONTREINDIC`) values('BACTIG10','BACTIGEL','ABC','Erythromycine','Ce médicament est utilisé en application locale pour traiter l''acné et les infections cutanées bactériennes associées.','Ce médicament est contre-indiqué en cas d''allergie aux antibiotiques de la famille des macrolides ou des lincosanides.');
insert into `MEDICAMENT`(`MED_DEPOTLEGAL`,`MED_NOMCOMMERCIAL`,`FAM_CODE`,`MED_COMPOSITION`,`MED_EFFETS`,`MED_CONTREINDIC`) values('BACTIV13','BACTIVIL','AFM','Erythromycine','Ce médicament est utilisé pour traiter des infections bactériennes spécifiques.','Ce médicament est contre-indiqué en cas d''allergie aux macrolides (dont le chef de file est l''érythromycine).');
insert into `MEDICAMENT`(`MED_DEPOTLEGAL`,`MED_NOMCOMMERCIAL`,`FAM_CODE`,`MED_COMPOSITION`,`MED_EFFETS`,`MED_CONTREINDIC`) values('BITALV','BIVALIC','AAA','Dextropropoxyphène + Paracétamol','Ce médicament est utilisé pour traiter les douleurs d''intensité modérée ou intense.','Ce médicament est contre-indiqué en cas d''allergie aux médicaments de cette famille, d''insuffisance hépatique ou d''insuffisance rénale.');
insert into `MEDICAMENT`(`MED_DEPOTLEGAL`,`MED_NOMCOMMERCIAL`,`FAM_CODE`,`MED_COMPOSITION`,`MED_EFFETS`,`MED_CONTREINDIC`) values('CARTION6','CARTION','AAA','Acide acétylsalicylique (aspirine) + Acide ascorbique (Vitamine C) + Paracétamol','Ce médicament est utilisé dans le traitement symptomatique de la douleur ou de la fièvre.','Ce médicament est contre-indiqué en cas de troubles de la coagulation (tendances aux hémorragies), d''ulcère gastroduodénal, maladies graves du foie.');
insert into `MEDICAMENT`(`MED_DEPOTLEGAL`,`MED_NOMCOMMERCIAL`,`FAM_CODE`,`MED_COMPOSITION`,`MED_EFFETS`,`MED_CONTREINDIC`) values('CLAZER6','CLAZER','AFM','Clarithromycine','Ce médicament est utilisé pour traiter des infections bactériennes spécifiques. Il est également utilisé dans le traitement de l''ulcère gastro-duodénal, en association avec d''autres médicaments.','Ce médicament est contre-indiqué en cas d''allergie aux macrolides (dont le chef de file est l''érythromycine).');
insert into `MEDICAMENT`(`MED_DEPOTLEGAL`,`MED_NOMCOMMERCIAL`,`FAM_CODE`,`MED_COMPOSITION`,`MED_EFFETS`,`MED_CONTREINDIC`) values('DEPRIL9','DEPRAMIL','AIM','Clomipramine','Ce médicament est utilisé pour traiter les épisodes dépressifs sévères, certaines douleurs rebelles, les troubles obsessionnels compulsifs et certaines énurésies chez l''enfant.','Ce médicament est contre-indiqué en cas de glaucome ou d''adénome de la prostate, d''infarctus récent, ou si vous avez reà§u un traitement par IMAO durant les 2 semaines précédentes ou en cas d''allergie aux antidépresseurs imipraminiques.');
insert into `MEDICAMENT`(`MED_DEPOTLEGAL`,`MED_NOMCOMMERCIAL`,`FAM_CODE`,`MED_COMPOSITION`,`MED_EFFETS`,`MED_CONTREINDIC`) values('DIMIRTAM6','DIMIRTAM','AAC','Mirtazapine','Ce médicament est utilisé pour traiter les épisodes dépressifs sévères.','La prise de ce produit est contre-indiquée en cas de d''allergie à  l''un des constituants.');
insert into `MEDICAMENT`(`MED_DEPOTLEGAL`,`MED_NOMCOMMERCIAL`,`FAM_CODE`,`MED_COMPOSITION`,`MED_EFFETS`,`MED_CONTREINDIC`) values('DOLRIL7','DOLORIL','AAA','Acide acétylsalicylique (aspirine) + Acide ascorbique (Vitamine C) + Paracétamol','Ce médicament est utilisé dans le traitement symptomatique de la douleur ou de la fièvre.','Ce médicament est contre-indiqué en cas d''allergie au paracétamol ou aux salicylates.');
insert into `MEDICAMENT`(`MED_DEPOTLEGAL`,`MED_NOMCOMMERCIAL`,`FAM_CODE`,`MED_COMPOSITION`,`MED_EFFETS`,`MED_CONTREINDIC`) values('DORNOM8','NORMADOR','HYP','Doxylamine','Ce médicament est utilisé pour traiter l''insomnie chez l''adulte.','Ce médicament est contre-indiqué en cas de glaucome, de certains troubles urinaires (rétention urinaire) et chez l''enfant de moins de 15 ans.');
insert into `MEDICAMENT`(`MED_DEPOTLEGAL`,`MED_NOMCOMMERCIAL`,`FAM_CODE`,`MED_COMPOSITION`,`MED_EFFETS`,`MED_CONTREINDIC`) values('EQUILARX6','EQUILAR','AAH','Méclozine','Ce médicament est utilisé pour traiter les vertiges et pour prévenir le mal des transports.','Ce médicament ne doit pas être utilisé en cas d''allergie au produit, en cas de glaucome ou de rétention urinaire.');
insert into `MEDICAMENT`(`MED_DEPOTLEGAL`,`MED_NOMCOMMERCIAL`,`FAM_CODE`,`MED_COMPOSITION`,`MED_EFFETS`,`MED_CONTREINDIC`) values('EVILR7','EVEILLOR','PSA','Adrafinil','Ce médicament est utilisé pour traiter les troubles de la vigilance et certains symptomes neurologiques chez le sujet agé.','Ce médicament est contre-indiqué en cas d''allergie à  l''un des constituants.');
insert into `MEDICAMENT`(`MED_DEPOTLEGAL`,`MED_NOMCOMMERCIAL`,`FAM_CODE`,`MED_COMPOSITION`,`MED_EFFETS`,`MED_CONTREINDIC`) values('INSXT5','INSECTIL','AH','Diphénydramine','Ce médicament est utilisé en application locale sur les piqûres d''insecte et l''urticaire.','Ce médicament est contre-indiqué en cas d''allergie aux antihistaminiques.');
insert into `MEDICAMENT`(`MED_DEPOTLEGAL`,`MED_NOMCOMMERCIAL`,`FAM_CODE`,`MED_COMPOSITION`,`MED_EFFETS`,`MED_CONTREINDIC`) values('JOVAI8','JOVENIL','AFM','Josamycine','Ce médicament est utilisé pour traiter des infections bactériennes spécifiques.','Ce médicament est contre-indiqué en cas d''allergie aux macrolides (dont le chef de file est l''érythromycine).');
insert into `MEDICAMENT`(`MED_DEPOTLEGAL`,`MED_NOMCOMMERCIAL`,`FAM_CODE`,`MED_COMPOSITION`,`MED_EFFETS`,`MED_CONTREINDIC`) values('LIDOXY23','LIDOXYTRACINE','AFC','Oxytétracycline +Lidocaïne','Ce médicament est utilisé en injection intramusculaire pour traiter certaines infections spécifiques.','Ce médicament est contre-indiqué en cas d''allergie à  l''un des constituants. Il ne doit pas être associé aux rétinoïdes.');
insert into `MEDICAMENT`(`MED_DEPOTLEGAL`,`MED_NOMCOMMERCIAL`,`FAM_CODE`,`MED_COMPOSITION`,`MED_EFFETS`,`MED_CONTREINDIC`) values('LITHOR12','LITHORINE','AP','Lithium','Ce médicament est indiqué dans la prévention des psychoses maniaco-dépressives ou pour traiter les états maniaques.','Ce médicament ne doit pas être utilisé si vous êtes allergique au lithium. Avant de prendre ce traitement, signalez à  votre médecin traitant si vous souffrez d''insuffisance rénale, ou si vous avez un régime sans sel.');
insert into `MEDICAMENT`(`MED_DEPOTLEGAL`,`MED_NOMCOMMERCIAL`,`FAM_CODE`,`MED_COMPOSITION`,`MED_EFFETS`,`MED_CONTREINDIC`) values('PARMOL16','PARMOCODEINE','AA','Codéine + Paracétamol','Ce médicament est utilisé pour le traitement des douleurs lorsque des antalgiques simples ne sont pas assez efficaces.','Ce médicament est contre-indiqué en cas d''allergie à  l''un des constituants, chez l''enfant de moins de 15 Kg, en cas d''insuffisance hépatique ou respiratoire, d''asthme, de phénylcétonurie et chez la femme qui allaite.');
insert into `MEDICAMENT`(`MED_DEPOTLEGAL`,`MED_NOMCOMMERCIAL`,`FAM_CODE`,`MED_COMPOSITION`,`MED_EFFETS`,`MED_CONTREINDIC`) values('PHYSOI8','PHYSICOR','PSA','Sulbutiamine','Ce médicament est utilisé pour traiter les baisses d''activité physique ou psychique, souvent dans un contexte de dépression.','Ce médicament est contre-indiqué en cas d''allergie à  l''un des constituants.');
insert into `MEDICAMENT`(`MED_DEPOTLEGAL`,`MED_NOMCOMMERCIAL`,`FAM_CODE`,`MED_COMPOSITION`,`MED_EFFETS`,`MED_CONTREINDIC`) values('PIRIZ8','PIRIZAN','ABA','Pyrazinamide','Ce médicament est utilisé, en association à  d''autres antibiotiques, pour traiter la tuberculose.','Ce médicament est contre-indiqué en cas d''allergie à  l''un des constituants, d''insuffisance rénale ou hépatique, d''hyperuricémie ou de porphyrie.');
insert into `MEDICAMENT`(`MED_DEPOTLEGAL`,`MED_NOMCOMMERCIAL`,`FAM_CODE`,`MED_COMPOSITION`,`MED_EFFETS`,`MED_CONTREINDIC`) values('POMDI20','POMADINE','AO','Bacitracine','Ce médicament est utilisé pour traiter les infections oculaires de la surface de l''oeil.','Ce médicament est contre-indiqué en cas d''allergie aux antibiotiques appliqués localement.');
insert into `MEDICAMENT`(`MED_DEPOTLEGAL`,`MED_NOMCOMMERCIAL`,`FAM_CODE`,`MED_COMPOSITION`,`MED_EFFETS`,`MED_CONTREINDIC`) values('TROXT21','TROXADET','AIN','Paroxétine','Ce médicament est utilisé pour traiter la dépression et les troubles obsessionnels compulsifs. Il peut également être utilisé en prévention des crises de panique avec ou sans agoraphobie.','Ce médicament est contre-indiqué en cas d''allergie au produit.');
insert into `MEDICAMENT`(`MED_DEPOTLEGAL`,`MED_NOMCOMMERCIAL`,`FAM_CODE`,`MED_COMPOSITION`,`MED_EFFETS`,`MED_CONTREINDIC`) values('TXISOL22','TOUXISOL Vitamine C','ALO','Tyrothricine + Acide ascorbique (Vitamine C)','Ce médicament est utilisé pour traiter les affections de la bouche et de la gorge.','Ce médicament est contre-indiqué en cas d''allergie à  l''un des constituants et chez l''enfant de moins de 6 ans.');
insert into `MEDICAMENT`(`MED_DEPOTLEGAL`,`MED_NOMCOMMERCIAL`,`FAM_CODE`,`MED_COMPOSITION`,`MED_EFFETS`,`MED_CONTREINDIC`) values('URIEG6','URIREGUL','AUM','Fosfomycine trométamol','Ce médicament est utilisé pour traiter les infections urinaires simples chez la femme de moins de 65 ans.','La prise de ce médicament est contre-indiquée en cas d''allergie à  l''un des constituants et d''insuffisance rénale.');

insert into `TYPE_PRATICIEN`(`TYP_CODE`,`TYP_LIBELLE`,`TYP_LIEU`) values('MH','Médecin Hospitalier','Hopital ou clinique');
insert into `TYPE_PRATICIEN`(`TYP_CODE`,`TYP_LIBELLE`,`TYP_LIEU`) values('MV','Médecine de Ville','Cabinet');
insert into `TYPE_PRATICIEN`(`TYP_CODE`,`TYP_LIBELLE`,`TYP_LIEU`) values('PH','Pharmacien Hospitalier','Hopital ou clinique');
insert into `TYPE_PRATICIEN`(`TYP_CODE`,`TYP_LIBELLE`,`TYP_LIEU`) values('PO','Pharmacien Officine','Pharmacie');
insert into `TYPE_PRATICIEN`(`TYP_CODE`,`TYP_LIBELLE`,`TYP_LIEU`) values('PS','Personnel de santé','Centre paramédical');

insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`PRA_COEFCONFIANCE`,`TYP_CODE`) values(1,'Notini','Alain','114 r Authie','85000','LA ROCHE SUR YON',290.03,9,'MH');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`PRA_COEFCONFIANCE`,`TYP_CODE`) values(2,'Gosselin','Albert','13 r Devon','41000','BLOIS',307.49,10,'MV');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`PRA_COEFCONFIANCE`,`TYP_CODE`) values(3,'Delahaye','André','36 av 6 Juin','25000','BESANCON',185.79,8,'PS');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`PRA_COEFCONFIANCE`,`TYP_CODE`) values(4,'Leroux','André','47 av Robert Schuman','60000','BEAUVAIS',172.04,7,'PH');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`PRA_COEFCONFIANCE`,`TYP_CODE`) values(5,'Desmoulins','Anne','31 r St Jean','30000','NIMES',94.75,6,'PO');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`PRA_COEFCONFIANCE`,`TYP_CODE`) values(6,'Mouel','Anne','27 r Auvergne','80000','AMIENS',45.2,5,'MH');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`PRA_COEFCONFIANCE`,`TYP_CODE`) values(7,'Desgranges-Lentz','Antoine','1 r Albert de Mun','29000','MORLAIX',20.07,3,'MV');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`PRA_COEFCONFIANCE`,`TYP_CODE`) values(8,'Marcouiller','Arnaud','31 r St Jean','68000','MULHOUSE',396.52,15,'PS');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`PRA_COEFCONFIANCE`,`TYP_CODE`) values(9,'Dupuy','Benoit','9 r Demolombe','34000','MONTPELLIER',395.66,14,'PH');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`PRA_COEFCONFIANCE`,`TYP_CODE`) values(10,'Lerat','Bernard','31 r St Jean','59000','LILLE',257.79,8,'PO');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`PRA_COEFCONFIANCE`,`TYP_CODE`) values(11,'Marçais-Lefebvre','Bertrand','86Bis r Basse','67000','STRASBOURG',450.96,18,'MH');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`PRA_COEFCONFIANCE`,`TYP_CODE`) values(12,'Boscher','Bruno','94 r Falaise','10000','TROYES',356.14,13,'MV');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`PRA_COEFCONFIANCE`,`TYP_CODE`) values(13,'Morel','Catherine','21 r Chateaubriand','75000','PARIS',379.57,14,'PS');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`PRA_COEFCONFIANCE`,`TYP_CODE`) values(14,'Guivarch','Chantal','4 av Gén Laperrine','45000','ORLEANS',114.56,6,'PH');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`PRA_COEFCONFIANCE`,`TYP_CODE`) values(15,'Bessin-Grosdoit','Christophe','92 r Falaise','6000','NICE',222.06,7,'PO');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`PRA_COEFCONFIANCE`,`TYP_CODE`) values(16,'Rossa','Claire','14 av Thiès','6000','NICE',529.78,20,'MH');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`PRA_COEFCONFIANCE`,`TYP_CODE`) values(17,'Cauchy','Denis','5 av Ste Thérèse','11000','NARBONNE',458.82,17,'MV');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`PRA_COEFCONFIANCE`,`TYP_CODE`) values(18,'Gaffé','Dominique','9 av 1ère Armée Française','35000','RENNES',213.4,6,'PS');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`PRA_COEFCONFIANCE`,`TYP_CODE`) values(19,'Guenon','Dominique','98 bd Mar Lyautey','44000','NANTES',175.89,15,'PH');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`PRA_COEFCONFIANCE`,`TYP_CODE`) values(20,'Prévot','Dominique','29 r Lucien Nelle','87000','LIMOGES',151.36,10,'PO');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`PRA_COEFCONFIANCE`,`TYP_CODE`) values(21,'Houchard','Eliane','9 r Demolombe','49100','ANGERS',436.96,18,'MH');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`PRA_COEFCONFIANCE`,`TYP_CODE`) values(22,'Desmons','Elisabeth','51 r Bernières','29000','QUIMPER',281.17,20,'MV');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`PRA_COEFCONFIANCE`,`TYP_CODE`) values(23,'Flament','Elisabeth','11 r Pasteur','35000','RENNES',315.6,15,'PS');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`PRA_COEFCONFIANCE`,`TYP_CODE`) values(24,'Goussard','Emmanuel','9 r Demolombe','41000','BLOIS',40.72,5,'PH');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`PRA_COEFCONFIANCE`,`TYP_CODE`) values(25,'Desprez','Eric','9 r Vaucelles','33000','BORDEAUX',406.85,16,'PO');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`PRA_COEFCONFIANCE`,`TYP_CODE`) values(26,'Coste','Evelyne','29 r Lucien Nelle','19000','TULLE',441.87,18,'MH');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`PRA_COEFCONFIANCE`,`TYP_CODE`) values(27,'Lefebvre','Frédéric','2 pl Wurzburg','55000','VERDUN',573.63,17,'MV');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`PRA_COEFCONFIANCE`,`TYP_CODE`) values(28,'Lemée','Frédéric','29 av 6 Juin','56000','VANNES',326.4,13,'PS');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`PRA_COEFCONFIANCE`,`TYP_CODE`) values(29,'Martin','Frédéric','Bât A 90 r Bayeux','70000','VESOUL',506.06,22,'PH');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`PRA_COEFCONFIANCE`,`TYP_CODE`) values(30,'Marie','Frédérique','172 r Caponière','70000','VESOUL',313.31,15,'PO');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`PRA_COEFCONFIANCE`,`TYP_CODE`) values(31,'Rosenstech','Geneviève','27 r Auvergne','75000','PARIS',366.82,14,'MH');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`PRA_COEFCONFIANCE`,`TYP_CODE`) values(32,'Pontavice','Ghislaine','8 r Gaillon','86000','POITIERS',265.58,15,'MV');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`PRA_COEFCONFIANCE`,`TYP_CODE`) values(33,'Leveneur-Mosquet','Guillaume','47 av Robert Schuman','64000','PAU',184.97,18,'PS');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`PRA_COEFCONFIANCE`,`TYP_CODE`) values(34,'Blanchais','Guy','30 r Authie','8000','SEDAN',502.48,17,'PH');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`PRA_COEFCONFIANCE`,`TYP_CODE`) values(35,'Leveneur','Hugues','7 pl St Gilles','62000','ARRAS',7.39,9,'PO');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`PRA_COEFCONFIANCE`,`TYP_CODE`) values(36,'Mosquet','Isabelle','22 r Jules Verne','76000','ROUEN',77.1,15,'MH');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`PRA_COEFCONFIANCE`,`TYP_CODE`) values(37,'Giraudon','Jean-Christophe','1 r Albert de Mun','38100','VIENNE',92.62,20,'MV');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`PRA_COEFCONFIANCE`,`TYP_CODE`) values(38,'Marie','Jean-Claude','26 r Hérouville','69000','LYON',120.1,19,'PS');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`PRA_COEFCONFIANCE`,`TYP_CODE`) values(39,'Maury','Jean-François','5 r Pierre Girard','71000','CHALON SUR SAONE',13.73,10,'PH');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`PRA_COEFCONFIANCE`,`TYP_CODE`) values(40,'Dennel','Jean-Louis','7 pl St Gilles','28000','CHARTRES',550.69,25,'PO');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`PRA_COEFCONFIANCE`,`TYP_CODE`) values(41,'Ain','Jean-Pierre','4 résid Olympia','2000','LAON',5.59,8,'MH');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`PRA_COEFCONFIANCE`,`TYP_CODE`) values(42,'Chemery','Jean-Pierre','51 pl Ancienne Boucherie','14000','CAEN',396.58,16,'MV');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`PRA_COEFCONFIANCE`,`TYP_CODE`) values(43,'Comoz','Jean-Pierre','35 r Auguste Lechesne','18000','BOURGES',340.35,18,'PS');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`PRA_COEFCONFIANCE`,`TYP_CODE`) values(44,'Desfaudais','Jean-Pierre','7 pl St Gilles','29000','BREST',71.76,14,'PH');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`PRA_COEFCONFIANCE`,`TYP_CODE`) values(45,'Phan','JérÃ´me','9 r Clos Caillet','79000','NIORT',451.61,23,'PO');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`PRA_COEFCONFIANCE`,`TYP_CODE`) values(46,'Riou','Line','43 bd Gén Vanier','77000','MARNE LA VALLEE',193.25,17,'MH');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`PRA_COEFCONFIANCE`,`TYP_CODE`) values(47,'Chubilleau','Louis','46 r Eglise','17000','SAINTES',202.07,16,'MV');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`PRA_COEFCONFIANCE`,`TYP_CODE`) values(48,'Lebrun','Lucette','178 r Auge','54000','NANCY',410.41,19,'PS');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`PRA_COEFCONFIANCE`,`TYP_CODE`) values(49,'Goessens','Marc','6 av 6 Juin','39000','DOLE',548.57,25,'PH');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`PRA_COEFCONFIANCE`,`TYP_CODE`) values(50,'Laforge','Marc','5 résid Prairie','50000','SAINT LO',265.05,17,'PO');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`PRA_COEFCONFIANCE`,`TYP_CODE`) values(51,'Millereau','Marc','36 av 6 Juin','72000','LA FERTE BERNARD',430.42,18,'MH');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`PRA_COEFCONFIANCE`,`TYP_CODE`) values(52,'Dauverne','Marie-Christine','69 av Charlemagne','21000','DIJON',281.05,22,'MV');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`PRA_COEFCONFIANCE`,`TYP_CODE`) values(53,'Vittorio','Myriam','3 pl Champlain','94000','BOISSY SAINT LEGER',356.23,7,'PS');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`PRA_COEFCONFIANCE`,`TYP_CODE`) values(54,'Lapasset','Nhieu','31 av 6 Juin','52000','CHAUMONT',107,24,'PH');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`PRA_COEFCONFIANCE`,`TYP_CODE`) values(55,'Plantet-Besnier','Nicole','10 av 1ère Armée Française','86000','CHATELLEREAULT',369.94,22,'PO');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`PRA_COEFCONFIANCE`,`TYP_CODE`) values(56,'Chubilleau','Pascal','3 r Hastings','15000','AURRILLAC',290.75,15,'MH');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`PRA_COEFCONFIANCE`,`TYP_CODE`) values(57,'Robert','Pascal','31 r St Jean','93000','BOBIGNY',162.41,12,'MV');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`PRA_COEFCONFIANCE`,`TYP_CODE`) values(58,'Jean','Pascale','114 r Authie','49100','SAUMUR',375.52,18,'PS');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`PRA_COEFCONFIANCE`,`TYP_CODE`) values(59,'Chanteloube','Patrice','14 av Thiès','13000','MARSEILLE',478.01,16,'PH');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`PRA_COEFCONFIANCE`,`TYP_CODE`) values(60,'Lecuirot','Patrice','résid St Pères 55 r Pigacière','54000','NANCY',239.66,21,'PO');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`PRA_COEFCONFIANCE`,`TYP_CODE`) values(61,'Gandon','Patrick','47 av Robert Schuman','37000','TOURS',599.06,25,'MH');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`PRA_COEFCONFIANCE`,`TYP_CODE`) values(62,'Mirouf','Patrick','22 r Puits Picard','74000','ANNECY',458.42,19,'MV');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`PRA_COEFCONFIANCE`,`TYP_CODE`) values(63,'Boireaux','Philippe','14 av Thiès','10000','CHALON EN CHAMPAGNE',454.48,23,'PS');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`PRA_COEFCONFIANCE`,`TYP_CODE`) values(64,'Cendrier','Philippe','7 pl St Gilles','12000','RODEZ',164.16,14,'PH');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`PRA_COEFCONFIANCE`,`TYP_CODE`) values(65,'Duhamel','Philippe','114 r Authie','34000','MONTPELLIER',98.62,12,'PO');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`PRA_COEFCONFIANCE`,`TYP_CODE`) values(66,'Grigy','Philippe','15 r Mélingue','44000','CLISSON',285.1,13,'MH');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`PRA_COEFCONFIANCE`,`TYP_CODE`) values(67,'Linard','Philippe','1 r Albert de Mun','81000','ALBI',486.3,15,'MV');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`PRA_COEFCONFIANCE`,`TYP_CODE`) values(68,'Lozier','Philippe','8 r Gaillon','31000','TOULOUSE',48.4,8,'PS');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`PRA_COEFCONFIANCE`,`TYP_CODE`) values(69,'Dechâtre','Pierre','63 av Thiès','23000','MONTLUCON',253.75,18,'PH');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`PRA_COEFCONFIANCE`,`TYP_CODE`) values(70,'Goessens','Pierre','22 r Jean Romain','40000','MONT DE MARSAN',426.19,17,'PO');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`PRA_COEFCONFIANCE`,`TYP_CODE`) values(71,'Leménager','Pierre','39 av 6 Juin','57000','METZ',118.7,13,'MH');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`PRA_COEFCONFIANCE`,`TYP_CODE`) values(72,'Née','Pierre','39 av 6 Juin','82000','MONTAUBAN',72.54,9,'MV');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`PRA_COEFCONFIANCE`,`TYP_CODE`) values(73,'Guyot','Pierre-Laurent','43 bd Gén Vanier','48000','MENDE',352.31,19,'PS');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`PRA_COEFCONFIANCE`,`TYP_CODE`) values(74,'Chauchard','Roger','9 r Vaucelles','13000','MARSEILLE',552.19,25,'PH');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`PRA_COEFCONFIANCE`,`TYP_CODE`) values(75,'Mabire','Roland','11 r Boutiques','67000','STRASBOURG',422.39,24,'PO');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`PRA_COEFCONFIANCE`,`TYP_CODE`) values(76,'Leroy','Soazig','45 r Boutiques','61000','ALENCON',570.67,25,'MH');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`PRA_COEFCONFIANCE`,`TYP_CODE`) values(77,'Guyot','Stéphane','26 r Hérouville','46000','FIGEAC',28.85,9,'MV');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`PRA_COEFCONFIANCE`,`TYP_CODE`) values(78,'Delposen','Sylvain','39 av 6 Juin','27000','DREUX',292.01,16,'PS');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`PRA_COEFCONFIANCE`,`TYP_CODE`) values(79,'Rault','Sylvie','15 bd Richemond','2000','SOISSON',526.6,22,'PH');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`PRA_COEFCONFIANCE`,`TYP_CODE`) values(80,'Renouf','Sylvie','98 bd Mar Lyautey','88000','EPINAL',425.24,25,'PO');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`PRA_COEFCONFIANCE`,`TYP_CODE`) values(81,'Alliet-Grach','Thierry','14 av Thiès','7000','PRIVAS',451.31,25,'MH');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`PRA_COEFCONFIANCE`,`TYP_CODE`) values(82,'Bayard','Thierry','92 r Falaise','42000','SAINT ETIENNE',271.71,18,'MV');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`PRA_COEFCONFIANCE`,`TYP_CODE`) values(83,'Gauchet','Thierry','7 r Desmoueux','38100','GRENOBLE',406.1,22,'PS');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`PRA_COEFCONFIANCE`,`TYP_CODE`) values(84,'Bobichon','Tristan','219 r Caponière','9000','FOIX',218.36,17,'PH');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`PRA_COEFCONFIANCE`,`TYP_CODE`) values(85,'Duchemin-Laniel','Véronique','130 r St Jean','33000','LIBOURNE',265.61,16,'PO');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`PRA_COEFCONFIANCE`,`TYP_CODE`) values(86,'Laurent','Younès','34 r Demolombe','53000','MAYENNE',496.1,23,'MH');

insert into `MOTIF`(`MOT_CODE`, `MOT_LIBELLE`) values ('ACTAN', 'Actualisation annuelle');
insert into `MOTIF`(`MOT_CODE`, `MOT_LIBELLE`) values ('BAIAC', 'Baisse activité');
insert into `MOTIF`(`MOT_CODE`, `MOT_LIBELLE`) values ('SOLPR', 'Sollicitation praticien');
insert into `MOTIF`(`MOT_CODE`, `MOT_LIBELLE`) values ('RAPAN', 'Rapport annuel');
insert into `MOTIF`(`MOT_CODE`, `MOT_LIBELLE`) values ('RELAN', 'Relance');
insert into `MOTIF`(`MOT_CODE`, `MOT_LIBELLE`) values ('AUTMO', 'Autre motif');


insert into `SECTEUR`(`SEC_CODE`,`SEC_LIBELLE`) values('E','Est');
insert into `SECTEUR`(`SEC_CODE`,`SEC_LIBELLE`) values('N','Nord');
insert into `SECTEUR`(`SEC_CODE`,`SEC_LIBELLE`) values('O','Ouest');
insert into `SECTEUR`(`SEC_CODE`,`SEC_LIBELLE`) values('P','Paris centre');
insert into `SECTEUR`(`SEC_CODE`,`SEC_LIBELLE`) values('S','Sud');

insert into `REGION`(`REG_CODE`,`SEC_CODE`,`REG_NOM`) values('AL','E','Alsace Lorraine');
insert into `REGION`(`REG_CODE`,`SEC_CODE`,`REG_NOM`) values('AQ','S','Aquitaine');
insert into `REGION`(`REG_CODE`,`SEC_CODE`,`REG_NOM`) values('AU','P','Auvergne');
insert into `REGION`(`REG_CODE`,`SEC_CODE`,`REG_NOM`) values('BG','O','Bretagne');
insert into `REGION`(`REG_CODE`,`SEC_CODE`,`REG_NOM`) values('BN','O','Basse Normandie');
insert into `REGION`(`REG_CODE`,`SEC_CODE`,`REG_NOM`) values('BO','E','Bourgogne');
insert into `REGION`(`REG_CODE`,`SEC_CODE`,`REG_NOM`) values('CA','N','Champagne Ardennes');
insert into `REGION`(`REG_CODE`,`SEC_CODE`,`REG_NOM`) values('CE','P','Centre');
insert into `REGION`(`REG_CODE`,`SEC_CODE`,`REG_NOM`) values('FC','E','Franche Comté');
insert into `REGION`(`REG_CODE`,`SEC_CODE`,`REG_NOM`) values('HN','N','Haute Normandie');
insert into `REGION`(`REG_CODE`,`SEC_CODE`,`REG_NOM`) values('IF','P','Ile de France');
insert into `REGION`(`REG_CODE`,`SEC_CODE`,`REG_NOM`) values('LG','S','Languedoc');
insert into `REGION`(`REG_CODE`,`SEC_CODE`,`REG_NOM`) values('LI','P','Limousin');
insert into `REGION`(`REG_CODE`,`SEC_CODE`,`REG_NOM`) values('MP','S','Midi Pyrénée');
insert into `REGION`(`REG_CODE`,`SEC_CODE`,`REG_NOM`) values('NP','N','Nord Pas de Calais');
insert into `REGION`(`REG_CODE`,`SEC_CODE`,`REG_NOM`) values('PA','S','Provence Alpes Cote d''Azur');
insert into `REGION`(`REG_CODE`,`SEC_CODE`,`REG_NOM`) values('PC','O','Poitou Charente');
insert into `REGION`(`REG_CODE`,`SEC_CODE`,`REG_NOM`) values('PI','N','Picardie');
insert into `REGION`(`REG_CODE`,`SEC_CODE`,`REG_NOM`) values('PL','O','Pays de Loire');
insert into `REGION`(`REG_CODE`,`SEC_CODE`,`REG_NOM`) values('RA','E','Rhone Alpes');
insert into `REGION`(`REG_CODE`,`SEC_CODE`,`REG_NOM`) values('RO','S','Roussilon');
insert into `REGION`(`REG_CODE`,`SEC_CODE`,`REG_NOM`) values('VD','O','Vendée');

insert into `COLLABORATEUR`(`COL_MATRICULE`,`COL_NOM`,`COL_PRENOM`,`COL_ADRESSE`,`COL_CP`,`COL_VILLE`,`COL_DATEEMBAUCHE`,`COL_LOGIN`,`COL_MDP`) values('a131','Villechalane','Louis','8 cours Lafontaine','29000','BREST','2002-12-11','lvillechalane','jux7g');
insert into `COLLABORATEUR`(`COL_MATRICULE`,`COL_NOM`,`COL_PRENOM`,`COL_ADRESSE`,`COL_CP`,`COL_VILLE`,`COL_DATEEMBAUCHE`,`COL_LOGIN`,`COL_MDP`) values('a17','Andre','David','1 r Aimon de Chissée','38100','GRENOBLE','2001-8-26','dandre','oppg5');
insert into `COLLABORATEUR`(`COL_MATRICULE`,`COL_NOM`,`COL_PRENOM`,`COL_ADRESSE`,`COL_CP`,`COL_VILLE`,`COL_DATEEMBAUCHE`,`COL_LOGIN`,`COL_MDP`) values('a55','Bedos','Christian','1 r Bénédictins','65000','TARBES','1997-7-17','cbedos','gmhxd');
insert into `COLLABORATEUR`(`COL_MATRICULE`,`COL_NOM`,`COL_PRENOM`,`COL_ADRESSE`,`COL_CP`,`COL_VILLE`,`COL_DATEEMBAUCHE`,`COL_LOGIN`,`COL_MDP`) values('a93','Tusseau','Louis','22 r Renou','86000','POITIERS','2009-1-2','ltusseau','ktp3s');
insert into `COLLABORATEUR`(`COL_MATRICULE`,`COL_NOM`,`COL_PRENOM`,`COL_ADRESSE`,`COL_CP`,`COL_VILLE`,`COL_DATEEMBAUCHE`,`COL_LOGIN`,`COL_MDP`) values('b13','Bentot','Pascal','11 av 6 Juin','67000','STRASBOURG','2006-3-11','pbentot','doyw1');
insert into `COLLABORATEUR`(`COL_MATRICULE`,`COL_NOM`,`COL_PRENOM`,`COL_ADRESSE`,`COL_CP`,`COL_VILLE`,`COL_DATEEMBAUCHE`,`COL_LOGIN`,`COL_MDP`) values('b16','Bioret','Luc','1 r Linne','35000','RENNES','2007-3-21','lbioret','hrjfs');
insert into `COLLABORATEUR`(`COL_MATRICULE`,`COL_NOM`,`COL_PRENOM`,`COL_ADRESSE`,`COL_CP`,`COL_VILLE`,`COL_DATEEMBAUCHE`,`COL_LOGIN`,`COL_MDP`) values('b19','Bunisset','Francis','10 r Nicolas Chorier','85000','LA ROCHE SUR YON','2009-1-31','fbunisset','4vbnd');
insert into `COLLABORATEUR`(`COL_MATRICULE`,`COL_NOM`,`COL_PRENOM`,`COL_ADRESSE`,`COL_CP`,`COL_VILLE`,`COL_DATEEMBAUCHE`,`COL_LOGIN`,`COL_MDP`) values('b25','Bunisset','Denise','1 r Lionne','49100','ANGERS','2004-7-3','dbunisset','s1y1r');
insert into `COLLABORATEUR`(`COL_MATRICULE`,`COL_NOM`,`COL_PRENOM`,`COL_ADRESSE`,`COL_CP`,`COL_VILLE`,`COL_DATEEMBAUCHE`,`COL_LOGIN`,`COL_MDP`) values('b28','Cacheux','Bernard','114 r Authie','34000','MONTPELLIER','2000-8-2','bcacheux','uf7r3');
insert into `COLLABORATEUR`(`COL_MATRICULE`,`COL_NOM`,`COL_PRENOM`,`COL_ADRESSE`,`COL_CP`,`COL_VILLE`,`COL_DATEEMBAUCHE`,`COL_LOGIN`,`COL_MDP`) values('b34','Cadic','Eric','123 r Caponière','41000','BLOIS','1995-1-15','ecadic','6u8dc');
insert into `COLLABORATEUR`(`COL_MATRICULE`,`COL_NOM`,`COL_PRENOM`,`COL_ADRESSE`,`COL_CP`,`COL_VILLE`,`COL_DATEEMBAUCHE`,`COL_LOGIN`,`COL_MDP`) values('b4','Charoze','Catherine','100 pl Géants','33000','BORDEAUX','2007-9-25','ccharoze','u817o');
insert into `COLLABORATEUR`(`COL_MATRICULE`,`COL_NOM`,`COL_PRENOM`,`COL_ADRESSE`,`COL_CP`,`COL_VILLE`,`COL_DATEEMBAUCHE`,`COL_LOGIN`,`COL_MDP`) values('b50','Clepkens','Christophe','12 r Fédérico Garcia Lorca','13000','MARSEILLE','2008-1-18','cclepkens','bw1us');
insert into `COLLABORATEUR`(`COL_MATRICULE`,`COL_NOM`,`COL_PRENOM`,`COL_ADRESSE`,`COL_CP`,`COL_VILLE`,`COL_DATEEMBAUCHE`,`COL_LOGIN`,`COL_MDP`) values('b59','Cottin','Vincent','36 sq Capucins','5000','GAP','2005-10-21','vcottin','2hoh9');
insert into `COLLABORATEUR`(`COL_MATRICULE`,`COL_NOM`,`COL_PRENOM`,`COL_ADRESSE`,`COL_CP`,`COL_VILLE`,`COL_DATEEMBAUCHE`,`COL_LOGIN`,`COL_MDP`) values('c14','Daburon','François','13 r Champs Elysées','6000','NICE','1990-9-1','fdaburon','7oqpv');
insert into `COLLABORATEUR`(`COL_MATRICULE`,`COL_NOM`,`COL_PRENOM`,`COL_ADRESSE`,`COL_CP`,`COL_VILLE`,`COL_DATEEMBAUCHE`,`COL_LOGIN`,`COL_MDP`) values('c3','De','Philippe','13 r Charles Peguy','10000','TROYES','2002-5-5','pde','gk9kx');
insert into `COLLABORATEUR`(`COL_MATRICULE`,`COL_NOM`,`COL_PRENOM`,`COL_ADRESSE`,`COL_CP`,`COL_VILLE`,`COL_DATEEMBAUCHE`,`COL_LOGIN`,`COL_MDP`) values('c54','Debelle','Michel','181 r Caponière','88000','EPINAL','2001-4-9','mdebelle','od5rt');
insert into `COLLABORATEUR`(`COL_MATRICULE`,`COL_NOM`,`COL_PRENOM`,`COL_ADRESSE`,`COL_CP`,`COL_VILLE`,`COL_DATEEMBAUCHE`,`COL_LOGIN`,`COL_MDP`) values('d13','Debelle','Jeanne','134 r Stalingrad','44000','NANTES','2001-12-5','jdebelle','nvwqq');
insert into `COLLABORATEUR`(`COL_MATRICULE`,`COL_NOM`,`COL_PRENOM`,`COL_ADRESSE`,`COL_CP`,`COL_VILLE`,`COL_DATEEMBAUCHE`,`COL_LOGIN`,`COL_MDP`) values('d51','Debroise','Michel','2 av 6 Juin','70000','VESOUL','1985-3-1','mdebroise','sghkb');
insert into `COLLABORATEUR`(`COL_MATRICULE`,`COL_NOM`,`COL_PRENOM`,`COL_ADRESSE`,`COL_CP`,`COL_VILLE`,`COL_DATEEMBAUCHE`,`COL_LOGIN`,`COL_MDP`) values('e22','Desmarquest','Nathalie','14 r Fédérico Garcia Lorca','54000','NANCY','1999-3-24','ndesmarquest','f1fob');
insert into `COLLABORATEUR`(`COL_MATRICULE`,`COL_NOM`,`COL_PRENOM`,`COL_ADRESSE`,`COL_CP`,`COL_VILLE`,`COL_DATEEMBAUCHE`,`COL_LOGIN`,`COL_MDP`) values('e24','Desnost','Pierre','16 r Barral de Montferrat','55000','VERDUN','2003-5-17','pdesnost','4k2o5');
insert into `COLLABORATEUR`(`COL_MATRICULE`,`COL_NOM`,`COL_PRENOM`,`COL_ADRESSE`,`COL_CP`,`COL_VILLE`,`COL_DATEEMBAUCHE`,`COL_LOGIN`,`COL_MDP`) values('e39','Dudouit','Frédéric','18 quai Xavier Jouvin','75000','PARIS','1998-4-26','fdudouit','44im8');
insert into `COLLABORATEUR`(`COL_MATRICULE`,`COL_NOM`,`COL_PRENOM`,`COL_ADRESSE`,`COL_CP`,`COL_VILLE`,`COL_DATEEMBAUCHE`,`COL_LOGIN`,`COL_MDP`) values('e49','Duncombe','Claude','19 av Alsace Lorraine','9000','FOIX','2006-2-19','cduncombe','qf77j');
insert into `COLLABORATEUR`(`COL_MATRICULE`,`COL_NOM`,`COL_PRENOM`,`COL_ADRESSE`,`COL_CP`,`COL_VILLE`,`COL_DATEEMBAUCHE`,`COL_LOGIN`,`COL_MDP`) values('e5','Enault-Pascreau','Céline','25B r Stalingrad','40000','MONT DE MARSAN','2000-11-27','cenault','y2qdu');
insert into `COLLABORATEUR`(`COL_MATRICULE`,`COL_NOM`,`COL_PRENOM`,`COL_ADRESSE`,`COL_CP`,`COL_VILLE`,`COL_DATEEMBAUCHE`,`COL_LOGIN`,`COL_MDP`) values('e52','Eynde','Valérie','3 r Henri Moissan','76000','ROUEN','2001-10-31','veynde','i7sn3');
insert into `COLLABORATEUR`(`COL_MATRICULE`,`COL_NOM`,`COL_PRENOM`,`COL_ADRESSE`,`COL_CP`,`COL_VILLE`,`COL_DATEEMBAUCHE`,`COL_LOGIN`,`COL_MDP`) values('f21','Finck','Jacques','rte Montreuil Bellay','74000','ANNECY','2003-6-8','jfinck','mpb3t');
insert into `COLLABORATEUR`(`COL_MATRICULE`,`COL_NOM`,`COL_PRENOM`,`COL_ADRESSE`,`COL_CP`,`COL_VILLE`,`COL_DATEEMBAUCHE`,`COL_LOGIN`,`COL_MDP`) values('f39','Frémont','Fernande','4 r Jean Giono','69000','LYON','2007-2-15','ffremont','xs5tq');
insert into `COLLABORATEUR`(`COL_MATRICULE`,`COL_NOM`,`COL_PRENOM`,`COL_ADRESSE`,`COL_CP`,`COL_VILLE`,`COL_DATEEMBAUCHE`,`COL_LOGIN`,`COL_MDP`) values('f4','Gest','Alain','30 r Authie','46000','FIGEAC','2004-5-3','agest','dywvt');
insert into `COLLABORATEUR`(`COL_MATRICULE`,`COL_NOM`,`COL_PRENOM`,`COL_ADRESSE`,`COL_CP`,`COL_VILLE`,`COL_DATEEMBAUCHE`,`COL_LOGIN`,`COL_MDP`) values('g19','Gheysen','Galassus','32 bd Mar Foch','75000','PARIS','2006-1-18','ggheysen','dv4q5');
insert into `COLLABORATEUR`(`COL_MATRICULE`,`COL_NOM`,`COL_PRENOM`,`COL_ADRESSE`,`COL_CP`,`COL_VILLE`,`COL_DATEEMBAUCHE`,`COL_LOGIN`,`COL_MDP`) values('g30','Girard','Yvon','31 av 6 Juin','80000','AMIENS','1988-6-15','ygirard','lz5f7r');
insert into `COLLABORATEUR`(`COL_MATRICULE`,`COL_NOM`,`COL_PRENOM`,`COL_ADRESSE`,`COL_CP`,`COL_VILLE`,`COL_DATEEMBAUCHE`,`COL_LOGIN`,`COL_MDP`) values('g53','Gombert','Luc','32 r Emile Gueymard','56000','VANNES','1995-10-2','lgombert','mp9s5z');
insert into `COLLABORATEUR`(`COL_MATRICULE`,`COL_NOM`,`COL_PRENOM`,`COL_ADRESSE`,`COL_CP`,`COL_VILLE`,`COL_DATEEMBAUCHE`,`COL_LOGIN`,`COL_MDP`) values('g7','Guindon','Caroline','40 r Mar Montgomery','87000','LIMOGES','2006-1-13','cguindon','qz2fd6');
insert into `COLLABORATEUR`(`COL_MATRICULE`,`COL_NOM`,`COL_PRENOM`,`COL_ADRESSE`,`COL_CP`,`COL_VILLE`,`COL_DATEEMBAUCHE`,`COL_LOGIN`,`COL_MDP`) values('h13','Guindon','François','44 r Picotière','19000','TULLE','2003-5-8','fguindon','kd6se7');
insert into `COLLABORATEUR`(`COL_MATRICULE`,`COL_NOM`,`COL_PRENOM`,`COL_ADRESSE`,`COL_CP`,`COL_VILLE`,`COL_DATEEMBAUCHE`,`COL_LOGIN`,`COL_MDP`) values('h30','Igigabel','Guy','33 gal Arlequin','94000','CRETEIL','2008-4-26','gigigabel','cd6hg8');
insert into `COLLABORATEUR`(`COL_MATRICULE`,`COL_NOM`,`COL_PRENOM`,`COL_ADRESSE`,`COL_CP`,`COL_VILLE`,`COL_DATEEMBAUCHE`,`COL_LOGIN`,`COL_MDP`) values('h35','Jourdren','Pierre','34 av Jean Perrot','15000','AURILLAC','2003-8-26','pjourdren','wv9f3u');
insert into `COLLABORATEUR`(`COL_MATRICULE`,`COL_NOM`,`COL_PRENOM`,`COL_ADRESSE`,`COL_CP`,`COL_VILLE`,`COL_DATEEMBAUCHE`,`COL_LOGIN`,`COL_MDP`) values('h40','Juttard','Pierre-Raoul','34 cours Jean Jaurès','8000','SEDAN','2002-11-1','prjuttard','vn3wj9');
insert into `COLLABORATEUR`(`COL_MATRICULE`,`COL_NOM`,`COL_PRENOM`,`COL_ADRESSE`,`COL_CP`,`COL_VILLE`,`COL_DATEEMBAUCHE`,`COL_LOGIN`,`COL_MDP`) values('j45','Labouré-Morel','Saout','38 cours Berriat','52000','CHAUMONT','2008-2-25','slaboure','jo5dt7');
insert into `COLLABORATEUR`(`COL_MATRICULE`,`COL_NOM`,`COL_PRENOM`,`COL_ADRESSE`,`COL_CP`,`COL_VILLE`,`COL_DATEEMBAUCHE`,`COL_LOGIN`,`COL_MDP`) values('j50','Landré','Philippe','4 av Gén Laperrine','59000','LILLE','2002-12-16','plandre','qx8hb6');
insert into `COLLABORATEUR`(`COL_MATRICULE`,`COL_NOM`,`COL_PRENOM`,`COL_ADRESSE`,`COL_CP`,`COL_VILLE`,`COL_DATEEMBAUCHE`,`COL_LOGIN`,`COL_MDP`) values('j8','Langeard','Hugues','39 av Jean Perrot','93000','BAGNOLET','2008-6-18','hlangeard','wp1sv8');
insert into `COLLABORATEUR`(`COL_MATRICULE`,`COL_NOM`,`COL_PRENOM`,`COL_ADRESSE`,`COL_CP`,`COL_VILLE`,`COL_DATEEMBAUCHE`,`COL_LOGIN`,`COL_MDP`) values('k4','Lanne','Bernard','4 r Bayeux','30000','NIMES','2006-11-21','blanne','uh2ds6');
insert into `COLLABORATEUR`(`COL_MATRICULE`,`COL_NOM`,`COL_PRENOM`,`COL_ADRESSE`,`COL_CP`,`COL_VILLE`,`COL_DATEEMBAUCHE`,`COL_LOGIN`,`COL_MDP`) values('k53','Le','Noël','4 av Beauvert','68000','MULHOUSE','1993-3-23','nle','pc2hg8');
insert into `COLLABORATEUR`(`COL_MATRICULE`,`COL_NOM`,`COL_PRENOM`,`COL_ADRESSE`,`COL_CP`,`COL_VILLE`,`COL_DATEEMBAUCHE`,`COL_LOGIN`,`COL_MDP`) values('l14','Le','Jean','39 r Raspail','53000','LAVAL','2005-2-2','jle','sx3frt5');
insert into `COLLABORATEUR`(`COL_MATRICULE`,`COL_NOM`,`COL_PRENOM`,`COL_ADRESSE`,`COL_CP`,`COL_VILLE`,`COL_DATEEMBAUCHE`,`COL_LOGIN`,`COL_MDP`) values('l23','Leclercq','Servane','11 r Quinconce','18000','BOURGES','2005-6-5','sleclercq','vg6dg3b');
insert into `COLLABORATEUR`(`COL_MATRICULE`,`COL_NOM`,`COL_PRENOM`,`COL_ADRESSE`,`COL_CP`,`COL_VILLE`,`COL_DATEEMBAUCHE`,`COL_LOGIN`,`COL_MDP`) values('l46','Lecornu','Jean-Bernard','4 bd Mar Foch','72000','LA FERTE BERNARD','2007-1-24','jblecornu','qw5ve6kn');
insert into `COLLABORATEUR`(`COL_MATRICULE`,`COL_NOM`,`COL_PRENOM`,`COL_ADRESSE`,`COL_CP`,`COL_VILLE`,`COL_DATEEMBAUCHE`,`COL_LOGIN`,`COL_MDP`) values('l56','Lecornu','Ludovic','4 r Abel Servien','25000','BESANCON','2006-2-27','llecornu','ad8vrt6v3');
insert into `COLLABORATEUR`(`COL_MATRICULE`,`COL_NOM`,`COL_PRENOM`,`COL_ADRESSE`,`COL_CP`,`COL_VILLE`,`COL_DATEEMBAUCHE`,`COL_LOGIN`,`COL_MDP`) values('m35','Lejard','Agnès','4 r Anthoard','82000','MONTAUBAN','1997-10-6','alejard','gf9tvw3');
insert into `COLLABORATEUR`(`COL_MATRICULE`,`COL_NOM`,`COL_PRENOM`,`COL_ADRESSE`,`COL_CP`,`COL_VILLE`,`COL_DATEEMBAUCHE`,`COL_LOGIN`,`COL_MDP`) values('m45','Lesaulnier','Pascal','47 r Thiers','57000','METZ','2000-10-13','plesaulnier','xvf8jhg6');
insert into `COLLABORATEUR`(`COL_MATRICULE`,`COL_NOM`,`COL_PRENOM`,`COL_ADRESSE`,`COL_CP`,`COL_VILLE`,`COL_DATEEMBAUCHE`,`COL_LOGIN`,`COL_MDP`) values('n42','Letessier','Stéphane','5 chem Capuche','27000','EVREUX','2006-3-6','sletessier','khy8dre2');
insert into `COLLABORATEUR`(`COL_MATRICULE`,`COL_NOM`,`COL_PRENOM`,`COL_ADRESSE`,`COL_CP`,`COL_VILLE`,`COL_DATEEMBAUCHE`,`COL_LOGIN`,`COL_MDP`) values('n58','Loirat','Didier','Les Pêchers cité Bourg la Croix','45000','ORLEANS','2002-8-30','dloirat','zdc5kju4');
insert into `COLLABORATEUR`(`COL_MATRICULE`,`COL_NOM`,`COL_PRENOM`,`COL_ADRESSE`,`COL_CP`,`COL_VILLE`,`COL_DATEEMBAUCHE`,`COL_LOGIN`,`COL_MDP`) values('n59','Maffezzoli','Thibaud','5 r Chateaubriand','2000','LAON','2004-12-19','tmaffezzoli','ijk7cfv2');
insert into `COLLABORATEUR`(`COL_MATRICULE`,`COL_NOM`,`COL_PRENOM`,`COL_ADRESSE`,`COL_CP`,`COL_VILLE`,`COL_DATEEMBAUCHE`,`COL_LOGIN`,`COL_MDP`) values('o26','Mancini','Anne','5 r D''Agier','48000','MENDE','2005-1-5','amancini','gsz9ybg3');
insert into `COLLABORATEUR`(`COL_MATRICULE`,`COL_NOM`,`COL_PRENOM`,`COL_ADRESSE`,`COL_CP`,`COL_VILLE`,`COL_DATEEMBAUCHE`,`COL_LOGIN`,`COL_MDP`) values('p32','Marcouiller','Gérard','7 pl St Gilles','91000','ISSY LES MOULINEAUX','2002-12-24','gmarcouiller','vgb2wse6');
insert into `COLLABORATEUR`(`COL_MATRICULE`,`COL_NOM`,`COL_PRENOM`,`COL_ADRESSE`,`COL_CP`,`COL_VILLE`,`COL_DATEEMBAUCHE`,`COL_LOGIN`,`COL_MDP`) values('p40','Michel','Jean-Claude','5 r Gabriel Péri','61000','FLERS','1992-7-10','jcmichel','xtr6khn5');
insert into `COLLABORATEUR`(`COL_MATRICULE`,`COL_NOM`,`COL_PRENOM`,`COL_ADRESSE`,`COL_CP`,`COL_VILLE`,`COL_DATEEMBAUCHE`,`COL_LOGIN`,`COL_MDP`) values('p41','Montecot','Françoise','6 r Paul Valéry','17000','SAINTES','2008-7-27','fmontecot','sxw8rjh2');
insert into `COLLABORATEUR`(`COL_MATRICULE`,`COL_NOM`,`COL_PRENOM`,`COL_ADRESSE`,`COL_CP`,`COL_VILLE`,`COL_DATEEMBAUCHE`,`COL_LOGIN`,`COL_MDP`) values('p42','Notini','Veronique','5 r Lieut Chabal','60000','BEAUVAIS','2004-12-12','vnotini','mqx9as4');
insert into `COLLABORATEUR`(`COL_MATRICULE`,`COL_NOM`,`COL_PRENOM`,`COL_ADRESSE`,`COL_CP`,`COL_VILLE`,`COL_DATEEMBAUCHE`,`COL_LOGIN`,`COL_MDP`) values('p49','Onfroy','Den','5 r Sidonie Jacolin','37000','TOURS','1987-10-3','donfroy','gru5kl3');
insert into `COLLABORATEUR`(`COL_MATRICULE`,`COL_NOM`,`COL_PRENOM`,`COL_ADRESSE`,`COL_CP`,`COL_VILLE`,`COL_DATEEMBAUCHE`,`COL_LOGIN`,`COL_MDP`) values('p6','Pascreau','Charles','57 bd Mar Foch','64000','PAU','2007-3-30','cpascreau','lfb3jn1');
insert into `COLLABORATEUR`(`COL_MATRICULE`,`COL_NOM`,`COL_PRENOM`,`COL_ADRESSE`,`COL_CP`,`COL_VILLE`,`COL_DATEEMBAUCHE`,`COL_LOGIN`,`COL_MDP`) values('p7','Pernot','Claude-Noël','6 r Alexandre 1 de Yougoslavie','11000','NARBONNE','2000-3-1','cnpernot','nyz27d');
insert into `COLLABORATEUR`(`COL_MATRICULE`,`COL_NOM`,`COL_PRENOM`,`COL_ADRESSE`,`COL_CP`,`COL_VILLE`,`COL_DATEEMBAUCHE`,`COL_LOGIN`,`COL_MDP`) values('p8','Perrier','Maître','6 r Aubert Dubayet','71000','CHALON SUR SAONE','2001-6-23','mperrier','ztf3ba4');
insert into `COLLABORATEUR`(`COL_MATRICULE`,`COL_NOM`,`COL_PRENOM`,`COL_ADRESSE`,`COL_CP`,`COL_VILLE`,`COL_DATEEMBAUCHE`,`COL_LOGIN`,`COL_MDP`) values('q17','Petit','Jean-Louis','7 r Ernest Renan','50000','SAINT LO','2007-9-6','jlpetit','qkp8ve1v');
insert into `COLLABORATEUR`(`COL_MATRICULE`,`COL_NOM`,`COL_PRENOM`,`COL_ADRESSE`,`COL_CP`,`COL_VILLE`,`COL_DATEEMBAUCHE`,`COL_LOGIN`,`COL_MDP`) values('r24','Piquery','Patrick','9 r Vaucelles','14000','CAEN','1994-7-29','ppiquery','va8drt9');
insert into `COLLABORATEUR`(`COL_MATRICULE`,`COL_NOM`,`COL_PRENOM`,`COL_ADRESSE`,`COL_CP`,`COL_VILLE`,`COL_DATEEMBAUCHE`,`COL_LOGIN`,`COL_MDP`) values('r58','Quiquandon','Joël','7 r Ernest Renan','29000','QUIMPER','2000-6-30','jquiquandon','bas5vr0');
insert into `COLLABORATEUR`(`COL_MATRICULE`,`COL_NOM`,`COL_PRENOM`,`COL_ADRESSE`,`COL_CP`,`COL_VILLE`,`COL_DATEEMBAUCHE`,`COL_LOGIN`,`COL_MDP`) values('s10','Retailleau','Josselin','88Bis r Saumuroise','39000','DOLE','2005-11-14','jretailleau','xg5nu3g');
insert into `COLLABORATEUR`(`COL_MATRICULE`,`COL_NOM`,`COL_PRENOM`,`COL_ADRESSE`,`COL_CP`,`COL_VILLE`,`COL_DATEEMBAUCHE`,`COL_LOGIN`,`COL_MDP`) values('s21','Retailleau','Pascal','32 bd Ayrault','23000','MONTLUCON','2002-9-25','pretailleau','bip6cnm3');
insert into `COLLABORATEUR`(`COL_MATRICULE`,`COL_NOM`,`COL_PRENOM`,`COL_ADRESSE`,`COL_CP`,`COL_VILLE`,`COL_DATEEMBAUCHE`,`COL_LOGIN`,`COL_MDP`) values('t43','Souron','Maryse','7B r Gay Lussac','21000','DIJON','2005-3-9','msouron','pui6de2');
insert into `COLLABORATEUR`(`COL_MATRICULE`,`COL_NOM`,`COL_PRENOM`,`COL_ADRESSE`,`COL_CP`,`COL_VILLE`,`COL_DATEEMBAUCHE`,`COL_LOGIN`,`COL_MDP`) values('t47','Tiphagne','Patrick','7B r Gay Lussac','62000','ARRAS','2007-8-29','ptiphagne','wrb7io2');
insert into `COLLABORATEUR`(`COL_MATRICULE`,`COL_NOM`,`COL_PRENOM`,`COL_ADRESSE`,`COL_CP`,`COL_VILLE`,`COL_DATEEMBAUCHE`,`COL_LOGIN`,`COL_MDP`) values('t55','Tréhet','Alain','7D chem Barral','12000','RODEZ','2004-11-29','atrehet','nyv7go');
insert into `COLLABORATEUR`(`COL_MATRICULE`,`COL_NOM`,`COL_PRENOM`,`COL_ADRESSE`,`COL_CP`,`COL_VILLE`,`COL_DATEEMBAUCHE`,`COL_LOGIN`,`COL_MDP`) values('t60','Tusseau','Josselin','63 r Bon Repos','28000','CHARTRES','2001-3-29','jtusseau','xzo6hy2');

insert into `RESPONSABLE`(`RES_MATRICULE`,`SEC_CODE`,`RES_DATENOMINATION`) values('b34','P', '2003-1-1');
insert into `RESPONSABLE`(`RES_MATRICULE`,`SEC_CODE`,`RES_DATENOMINATION`) values('c14','S', '2015-1-2');
insert into `RESPONSABLE`(`RES_MATRICULE`,`SEC_CODE`,`RES_DATENOMINATION`) values('d51','E', '2000-7-1');
insert into `RESPONSABLE`(`RES_MATRICULE`,`SEC_CODE`,`RES_DATENOMINATION`) values('g30','N', '2013-9-1');
insert into `RESPONSABLE`(`RES_MATRICULE`,`SEC_CODE`,`RES_DATENOMINATION`) values('p40','O', '2010-7-1');

insert into `DELEGUE_REGIONAL`(`DEL_MATRICULE`,`REG_CODE`, `DEL_DATEPROMOTION`) values('a17','RA', '2009-9-19');
insert into `DELEGUE_REGIONAL`(`DEL_MATRICULE`,`REG_CODE`, `DEL_DATEPROMOTION`) values('a55','RO', '2013-8-21');
insert into `DELEGUE_REGIONAL`(`DEL_MATRICULE`,`REG_CODE`, `DEL_DATEPROMOTION`) values('b25','CE', '2006-7-1');
insert into `DELEGUE_REGIONAL`(`DEL_MATRICULE`,`REG_CODE`, `DEL_DATEPROMOTION`) values('d13','PL', '2008-12-5');
insert into `DELEGUE_REGIONAL`(`DEL_MATRICULE`,`REG_CODE`, `DEL_DATEPROMOTION`) values('e24','AL', '2015-4-30');
insert into `DELEGUE_REGIONAL`(`DEL_MATRICULE`,`REG_CODE`, `DEL_DATEPROMOTION`) values('t43','BG', '2007-5-15');
insert into `DELEGUE_REGIONAL`(`DEL_MATRICULE`,`REG_CODE`, `DEL_DATEPROMOTION`) values('g7','LI', '2011-1-13');
insert into `DELEGUE_REGIONAL`(`DEL_MATRICULE`,`REG_CODE`, `DEL_DATEPROMOTION`) values('k53','CA', '2002-4-3');
insert into `DELEGUE_REGIONAL`(`DEL_MATRICULE`,`REG_CODE`, `DEL_DATEPROMOTION`) values('b28','LG', '2013-1-2');
insert into `DELEGUE_REGIONAL`(`DEL_MATRICULE`,`REG_CODE`, `DEL_DATEPROMOTION`) values('p42','PI', '2009-1-1');
insert into `DELEGUE_REGIONAL`(`DEL_MATRICULE`,`REG_CODE`, `DEL_DATEPROMOTION`) values('j45','FC', '2008-2-25');
insert into `DELEGUE_REGIONAL`(`DEL_MATRICULE`,`REG_CODE`, `DEL_DATEPROMOTION`) values('j8','IF', '2010-6-1');
insert into `DELEGUE_REGIONAL`(`DEL_MATRICULE`,`REG_CODE`, `DEL_DATEPROMOTION`) values('r24','BN', '2008-5-25');
insert into `DELEGUE_REGIONAL`(`DEL_MATRICULE`,`REG_CODE`, `DEL_DATEPROMOTION`) values('b4','AQ', '2012-7-1');

insert into `RAPPORT_VISITE`(`COL_MATRICULE`,`RAP_NUM`,`PRA_NUM`,`PRA_NUM_REMPLACANT`,`RAP_DATE_VISITE`,`RAP_DATE_SAISIE`,`RAP_BILAN`,`RAP_MOTIF_AUTRE`,`MOT_CODE`,`RAP_DOCUMENTATION`,`RAP_SAISIEDEFINITIVE`) values('a131',3,23,null,'2002-4-18','2002-4-25','Médecin curieux, à recontacer en décembre pour réunion',null,'ACTAN',1,0);
insert into `RAPPORT_VISITE`(`COL_MATRICULE`,`RAP_NUM`,`PRA_NUM`,`PRA_NUM_REMPLACANT`,`RAP_DATE_VISITE`,`RAP_DATE_SAISIE`,`RAP_BILAN`,`RAP_MOTIF_AUTRE`,`MOT_CODE`,`RAP_DOCUMENTATION`,`RAP_SAISIEDEFINITIVE`) values('a131',7,41,null,'2003-3-23','2003-3-30','RAS Changement de tel : 05 89 89 89 89',null,'RAPAN',0,0);
insert into `RAPPORT_VISITE`(`COL_MATRICULE`,`RAP_NUM`,`PRA_NUM`,`PRA_NUM_REMPLACANT`,`RAP_DATE_VISITE`,`RAP_DATE_SAISIE`,`RAP_BILAN`,`RAP_MOTIF_AUTRE`,`MOT_CODE`,`RAP_DOCUMENTATION`,`RAP_SAISIEDEFINITIVE`) values('a17',4,4,null,'2003-5-21','2003-5-28','Changement de direction, redéfinition de la politique médicamenteuse, recours au générique',null,'BAIAC',0,0);

insert into `TRAVAILLER`(`COL_MATRICULE`,`DATE_DEBUT`,`REG_CODE`, `DATE_FIN`) values('p49','1987-10-3','CE', null);
insert into `TRAVAILLER`(`COL_MATRICULE`,`DATE_DEBUT`,`REG_CODE`, `DATE_FIN`) values('k53','1993-3-23','AL', '2002-4-2');
insert into `TRAVAILLER`(`COL_MATRICULE`,`DATE_DEBUT`,`REG_CODE`, `DATE_FIN`) values('r24','1994-7-29','BG', '2008-5-24');
insert into `TRAVAILLER`(`COL_MATRICULE`,`DATE_DEBUT`,`REG_CODE`, `DATE_FIN`) values('g53','1995-10-2','BG', '2009-3-26');
insert into `TRAVAILLER`(`COL_MATRICULE`,`DATE_DEBUT`,`REG_CODE`, `DATE_FIN`) values('a55','1997-7-17','RA', '2005-5-18');
insert into `TRAVAILLER`(`COL_MATRICULE`,`DATE_DEBUT`,`REG_CODE`, `DATE_FIN`) values('m35','1997-10-6','MP', null);
insert into `TRAVAILLER`(`COL_MATRICULE`,`DATE_DEBUT`,`REG_CODE`, `DATE_FIN`) values('e39','1998-4-26','IF', null);
insert into `TRAVAILLER`(`COL_MATRICULE`,`DATE_DEBUT`,`REG_CODE`, `DATE_FIN`) values('c3','1999-2-1','PA', '2002-5-4');
insert into `TRAVAILLER`(`COL_MATRICULE`,`DATE_DEBUT`,`REG_CODE`, `DATE_FIN`) values('e22','1999-3-24','AL', '2012-3-19');
insert into `TRAVAILLER`(`COL_MATRICULE`,`DATE_DEBUT`,`REG_CODE`, `DATE_FIN`) values('p7','2000-3-1','RO', null);
insert into `TRAVAILLER`(`COL_MATRICULE`,`DATE_DEBUT`,`REG_CODE`, `DATE_FIN`) values('r58','2000-6-30','BG', null);
insert into `TRAVAILLER`(`COL_MATRICULE`,`DATE_DEBUT`,`REG_CODE`, `DATE_FIN`) values('m45','2000-10-13','HN', '2009-4-7');
insert into `TRAVAILLER`(`COL_MATRICULE`,`DATE_DEBUT`,`REG_CODE`, `DATE_FIN`) values('e5','2000-11-27','MP', '2005-11-26');
insert into `TRAVAILLER`(`COL_MATRICULE`,`DATE_DEBUT`,`REG_CODE`, `DATE_FIN`) values('t60','2001-3-29','CE', null);
insert into `TRAVAILLER`(`COL_MATRICULE`,`DATE_DEBUT`,`REG_CODE`, `DATE_FIN`) values('c54','2001-4-9','AL', '2011-3-2');
insert into `TRAVAILLER`(`COL_MATRICULE`,`DATE_DEBUT`,`REG_CODE`, `DATE_FIN`) values('p8','2001-6-23','BO', null);
insert into `TRAVAILLER`(`COL_MATRICULE`,`DATE_DEBUT`,`REG_CODE`, `DATE_FIN`) values('a17','2001-8-26','LI', '2007-9-18');
insert into `TRAVAILLER`(`COL_MATRICULE`,`DATE_DEBUT`,`REG_CODE`, `DATE_FIN`) values('e52','2001-10-31','HN', null);
insert into `TRAVAILLER`(`COL_MATRICULE`,`DATE_DEBUT`,`REG_CODE`, `DATE_FIN`) values('d13','2001-12-5','PL', null);
insert into `TRAVAILLER`(`COL_MATRICULE`,`DATE_DEBUT`,`REG_CODE`, `DATE_FIN`) values('k53','2002-4-3','CA', null);
insert into `TRAVAILLER`(`COL_MATRICULE`,`DATE_DEBUT`,`REG_CODE`, `DATE_FIN`) values('c3','2002-5-5','CA', null);
insert into `TRAVAILLER`(`COL_MATRICULE`,`DATE_DEBUT`,`REG_CODE`, `DATE_FIN`) values('n58','2002-8-30','CE', null);
insert into `TRAVAILLER`(`COL_MATRICULE`,`DATE_DEBUT`,`REG_CODE`, `DATE_FIN`) values('s21','2002-9-25','LI', null);
insert into `TRAVAILLER`(`COL_MATRICULE`,`DATE_DEBUT`,`REG_CODE`, `DATE_FIN`) values('h40','2002-11-1','CA', null);
insert into `TRAVAILLER`(`COL_MATRICULE`,`DATE_DEBUT`,`REG_CODE`, `DATE_FIN`) values('a131','2002-12-11','BN', null);
insert into `TRAVAILLER`(`COL_MATRICULE`,`DATE_DEBUT`,`REG_CODE`, `DATE_FIN`) values('p42','2002-12-14','BN', '2004-12-11');
insert into `TRAVAILLER`(`COL_MATRICULE`,`DATE_DEBUT`,`REG_CODE`, `DATE_FIN`) values('j50','2002-12-16','NP', null);
insert into `TRAVAILLER`(`COL_MATRICULE`,`DATE_DEBUT`,`REG_CODE`, `DATE_FIN`) values('p32','2002-12-24','IF', null);
insert into `TRAVAILLER`(`COL_MATRICULE`,`DATE_DEBUT`,`REG_CODE`, `DATE_FIN`) values('h13','2003-5-8','LI', null);
insert into `TRAVAILLER`(`COL_MATRICULE`,`DATE_DEBUT`,`REG_CODE`, `DATE_FIN`) values('e24','2003-5-17','BG', '2012-2-28');
insert into `TRAVAILLER`(`COL_MATRICULE`,`DATE_DEBUT`,`REG_CODE`, `DATE_FIN`) values('f21','2003-6-8','RA', null);
insert into `TRAVAILLER`(`COL_MATRICULE`,`DATE_DEBUT`,`REG_CODE`, `DATE_FIN`) values('h35','2003-8-26','AU', null);
insert into `TRAVAILLER`(`COL_MATRICULE`,`DATE_DEBUT`,`REG_CODE`, `DATE_FIN`) values('b25','2003-12-6','CE', '2004-7-2');
insert into `TRAVAILLER`(`COL_MATRICULE`,`DATE_DEBUT`,`REG_CODE`, `DATE_FIN`) values('f4','2004-5-3','MP', null);
insert into `TRAVAILLER`(`COL_MATRICULE`,`DATE_DEBUT`,`REG_CODE`, `DATE_FIN`) values('b25','2004-7-3','PL', '2009-6-17');
insert into `TRAVAILLER`(`COL_MATRICULE`,`DATE_DEBUT`,`REG_CODE`, `DATE_FIN`) values('t55','2004-11-29','MP', null);
insert into `TRAVAILLER`(`COL_MATRICULE`,`DATE_DEBUT`,`REG_CODE`, `DATE_FIN`) values('p42','2004-12-12','PI', null);
insert into `TRAVAILLER`(`COL_MATRICULE`,`DATE_DEBUT`,`REG_CODE`, `DATE_FIN`) values('n59','2004-12-19','PI', null);
insert into `TRAVAILLER`(`COL_MATRICULE`,`DATE_DEBUT`,`REG_CODE`, `DATE_FIN`) values('o26','2005-1-5','LG', null);
insert into `TRAVAILLER`(`COL_MATRICULE`,`DATE_DEBUT`,`REG_CODE`, `DATE_FIN`) values('l14','2005-2-2','PL', null);
insert into `TRAVAILLER`(`COL_MATRICULE`,`DATE_DEBUT`,`REG_CODE`, `DATE_FIN`) values('t43','2005-3-9','BO', '2006-5-26');
insert into `TRAVAILLER`(`COL_MATRICULE`,`DATE_DEBUT`,`REG_CODE`, `DATE_FIN`) values('a55','2005-5-19','MP', '2009-8-20');
insert into `TRAVAILLER`(`COL_MATRICULE`,`DATE_DEBUT`,`REG_CODE`, `DATE_FIN`) values('l23','2005-6-5','PC', null);
insert into `TRAVAILLER`(`COL_MATRICULE`,`DATE_DEBUT`,`REG_CODE`, `DATE_FIN`) values('b59','2005-10-21','RA', null);
insert into `TRAVAILLER`(`COL_MATRICULE`,`DATE_DEBUT`,`REG_CODE`, `DATE_FIN`) values('s10','2005-11-14','FC', null);
insert into `TRAVAILLER`(`COL_MATRICULE`,`DATE_DEBUT`,`REG_CODE`, `DATE_FIN`) values('e5','2005-11-27','PA', '2010-11-26');
insert into `TRAVAILLER`(`COL_MATRICULE`,`DATE_DEBUT`,`REG_CODE`, `DATE_FIN`) values('g7','2006-1-13','LI', null);
insert into `TRAVAILLER`(`COL_MATRICULE`,`DATE_DEBUT`,`REG_CODE`, `DATE_FIN`) values('g19','2006-1-18','IF', null);
insert into `TRAVAILLER`(`COL_MATRICULE`,`DATE_DEBUT`,`REG_CODE`, `DATE_FIN`) values('e49','2006-2-19','MP', null);
insert into `TRAVAILLER`(`COL_MATRICULE`,`DATE_DEBUT`,`REG_CODE`, `DATE_FIN`) values('l56','2006-2-27','FC', null);
insert into `TRAVAILLER`(`COL_MATRICULE`,`DATE_DEBUT`,`REG_CODE`, `DATE_FIN`) values('n42','2006-3-6','HN', null);
insert into `TRAVAILLER`(`COL_MATRICULE`,`DATE_DEBUT`,`REG_CODE`, `DATE_FIN`) values('b13','2006-3-11','AL', null);
insert into `TRAVAILLER`(`COL_MATRICULE`,`DATE_DEBUT`,`REG_CODE`, `DATE_FIN`) values('t43','2006-5-27','BG', null);
insert into `TRAVAILLER`(`COL_MATRICULE`,`DATE_DEBUT`,`REG_CODE`, `DATE_FIN`) values('k4','2006-11-21','LG', null);
insert into `TRAVAILLER`(`COL_MATRICULE`,`DATE_DEBUT`,`REG_CODE`, `DATE_FIN`) values('l46','2007-1-24','PL', null);
insert into `TRAVAILLER`(`COL_MATRICULE`,`DATE_DEBUT`,`REG_CODE`, `DATE_FIN`) values('c14','2007-2-1','PA', null);
insert into `TRAVAILLER`(`COL_MATRICULE`,`DATE_DEBUT`,`REG_CODE`, `DATE_FIN`) values('f39','2007-2-15','RA', null);
insert into `TRAVAILLER`(`COL_MATRICULE`,`DATE_DEBUT`,`REG_CODE`, `DATE_FIN`) values('b16','2007-3-21','BG', null);
insert into `TRAVAILLER`(`COL_MATRICULE`,`DATE_DEBUT`,`REG_CODE`, `DATE_FIN`) values('p6','2007-3-30','AQ', null);
insert into `TRAVAILLER`(`COL_MATRICULE`,`DATE_DEBUT`,`REG_CODE`, `DATE_FIN`) values('t47','2007-8-29','PI', null);
insert into `TRAVAILLER`(`COL_MATRICULE`,`DATE_DEBUT`,`REG_CODE`, `DATE_FIN`) values('q17','2007-9-6','BN', null);
insert into `TRAVAILLER`(`COL_MATRICULE`,`DATE_DEBUT`,`REG_CODE`, `DATE_FIN`) values('a17','2007-9-19','RA', null);
insert into `TRAVAILLER`(`COL_MATRICULE`,`DATE_DEBUT`,`REG_CODE`, `DATE_FIN`) values('b4','2007-9-25','AQ', null);
insert into `TRAVAILLER`(`COL_MATRICULE`,`DATE_DEBUT`,`REG_CODE`, `DATE_FIN`) values('b50','2008-1-18','PA', null);
insert into `TRAVAILLER`(`COL_MATRICULE`,`DATE_DEBUT`,`REG_CODE`, `DATE_FIN`) values('j45','2008-2-25','FC', null);
insert into `TRAVAILLER`(`COL_MATRICULE`,`DATE_DEBUT`,`REG_CODE`, `DATE_FIN`) values('h30','2008-4-26','IF', null);
insert into `TRAVAILLER`(`COL_MATRICULE`,`DATE_DEBUT`,`REG_CODE`, `DATE_FIN`) values('r24','2008-5-25','BN', null);
insert into `TRAVAILLER`(`COL_MATRICULE`,`DATE_DEBUT`,`REG_CODE`, `DATE_FIN`) values('j8','2008-6-18','IF', null);
insert into `TRAVAILLER`(`COL_MATRICULE`,`DATE_DEBUT`,`REG_CODE`, `DATE_FIN`) values('p41','2008-7-27','PC', null);
insert into `TRAVAILLER`(`COL_MATRICULE`,`DATE_DEBUT`,`REG_CODE`, `DATE_FIN`) values('a93','2009-1-2','PC', null);
insert into `TRAVAILLER`(`COL_MATRICULE`,`DATE_DEBUT`,`REG_CODE`, `DATE_FIN`) values('b19','2009-1-31','PL', null);
insert into `TRAVAILLER`(`COL_MATRICULE`,`DATE_DEBUT`,`REG_CODE`, `DATE_FIN`) values('g53','2009-3-27','PL', '2010-10-30');
insert into `TRAVAILLER`(`COL_MATRICULE`,`DATE_DEBUT`,`REG_CODE`, `DATE_FIN`) values('m45','2009-4-8','AL', null);
insert into `TRAVAILLER`(`COL_MATRICULE`,`DATE_DEBUT`,`REG_CODE`, `DATE_FIN`) values('b25','2009-6-18','CE', null);
insert into `TRAVAILLER`(`COL_MATRICULE`,`DATE_DEBUT`,`REG_CODE`, `DATE_FIN`) values('p40','1992-7-10','BN', '2010-6-30');
insert into `TRAVAILLER`(`COL_MATRICULE`,`DATE_DEBUT`,`REG_CODE`, `DATE_FIN`) values('a55','2009-8-21','RO', null);
insert into `TRAVAILLER`(`COL_MATRICULE`,`DATE_DEBUT`,`REG_CODE`, `DATE_FIN`) values('e24','2012-2-29','AL', null);
insert into `TRAVAILLER`(`COL_MATRICULE`,`DATE_DEBUT`,`REG_CODE`, `DATE_FIN`) values('b28','2010-8-2','LG', null);
insert into `TRAVAILLER`(`COL_MATRICULE`,`DATE_DEBUT`,`REG_CODE`, `DATE_FIN`) values('g53','2010-10-31','PI', null);
insert into `TRAVAILLER`(`COL_MATRICULE`,`DATE_DEBUT`,`REG_CODE`, `DATE_FIN`) values('e5','2010-11-27','AQ', null);
insert into `TRAVAILLER`(`COL_MATRICULE`,`DATE_DEBUT`,`REG_CODE`, `DATE_FIN`) values('c54','2011-3-3','PA', null);
insert into `TRAVAILLER`(`COL_MATRICULE`,`DATE_DEBUT`,`REG_CODE`, `DATE_FIN`) values('e22','2012-3-20','FC', null);
insert into `TRAVAILLER`(`COL_MATRICULE`,`DATE_DEBUT`,`REG_CODE`, `DATE_FIN`) values('b34', '1995-1-15','AL', '2002-12-31');
insert into `TRAVAILLER`(`COL_MATRICULE`,`DATE_DEBUT`,`REG_CODE`, `DATE_FIN`) values('c14', '1990-9-1','BG', '2015-1-31');
insert into `TRAVAILLER`(`COL_MATRICULE`,`DATE_DEBUT`,`REG_CODE`, `DATE_FIN`) values('d51', '1985-3-1','RO', '2000-6-30');
insert into `TRAVAILLER`(`COL_MATRICULE`,`DATE_DEBUT`,`REG_CODE`, `DATE_FIN`) values('g30', '1988-6-15','IF', '2013-8-31');


insert into `OFFRIR`(`COL_MATRICULE`,`RAP_NUM`,`MED_DEPOTLEGAL`,`OFF_QTE`) values('a17',4,'3MYC7',3);
insert into `OFFRIR`(`COL_MATRICULE`,`RAP_NUM`,`MED_DEPOTLEGAL`,`OFF_QTE`) values('a17',4,'AMOX45',12);
commit;
